import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
await p.goto("http://localhost:3001/", { waitUntil: "networkidle", timeout: 60000 });
await p.locator("#gallery").scrollIntoViewIfNeeded();
await p.waitForTimeout(500);
await p.locator('#gallery button[aria-label^="Enlarge"]').first().click();
await p.waitForTimeout(700);
await p.screenshot({ path: "/tmp/rp/mine-gallery-lightbox.png" });
await b.close();
console.log("DONE");
